---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: Dahl Home

description: Dahl House Homepage

background: 
  image: https://wallpapercat.com/w/full/8/7/7/194290-3840x2160-desktop-4k-outer-space-wallpaper-photo.jpg
  blur: md
  saturate: 50
  brightness: 10
  opacity: 40

layout:
  Links:
    header: false
  Calendar:
    header: false
  Home Network:
    style: row
    columns: 2
  Home Media Server:
    style: row
    columns: 2
  Dahl Home ARR:
    style: row
    columns: 4
  Dahl Home Download:



  Portainer:
  Server Manage:

  Server:
    style: row
    columns: 2
    
disableCollapse: true
providers:
  openweathermap: openweathermapapikey
  weatherapi: "{{HOMEPAGE_VAR_WEATHERAPI_API_KEY}}"
  finnhub: "{{HOMEPAGE_VAR_FINNHUB_API_KEY}}"

headerStyle: boxed


hideErrors: true

hideVersion: true

useEqualHeights: true